Import Numpy

In [2]:
import numpy as np

### Creating a 1d array of integers

In [3]:
x=np.array([1,2,3,4,5])
print(x)
print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
x.dtype # returns the datatypes stored in numpy arrays

dtype('int64')

In [5]:
x.shape #number of dimensions in the ararys

(5,)

## Creating a 2dimensional numpy array

In [8]:
Y=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(Y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [9]:
Y.shape

(4, 3)

In [10]:
Y.size #total number of elements in the arrays

12

In [12]:
x=np.array(['Hello', "World"])
print(x)
print(type(x))
print(x.dtype) #stores strings as unicode characters
# the numpy automatically assigns the datatype to the elements

['Hello' 'World']
<class 'numpy.ndarray'>
<U5


### Creating a 1d array of elements having different types

In [13]:
# unlike python list the numpy lists must contain the elements of the same datatype
x=np.array([1,2,3,'Hello', "World"])
print(x)
print(type(x))
print(x.dtype)
#each element having same datatype assigned by the numpy

['1' '2' '3' 'Hello' 'World']
<class 'numpy.ndarray'>
<U21


In [14]:
x=np.array([1,2,5.6,4.6])
print(type(x))
print(x.dtype) # assigns float to all the data called as upcasting

<class 'numpy.ndarray'>
float64


### Creating arrays having default datatype

In [15]:
# we can also specify our default datatype
x=np.array([1,2,5.6,4.6], dtype=np.int64)
print(type(x))
print(x.dtype) # assigns float to all the data called as upcasting

<class 'numpy.ndarray'>
int64


### Saving and loading a numpy array

In [16]:
# We can save and store a numpy array using save function 
x=np.array([1,2,3,4])
np.save('my_array',x)

In [17]:
# load the saved array by using load() 
y=np.load('my_array.npy')
print(y)

[1 2 3 4]


### Rank (dimension) of an array

In [18]:
x.ndim # the number of dimensions is called rank 


1

# Creating numpy arrays using builtin functions

In [20]:
X=np.zeros((3,4))
print(X)
print(type(X))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<class 'numpy.ndarray'>


In [21]:
X.dtype #by defult it creates a datatype float64a

dtype('float64')

### Creating arrays with a default dtype

In [25]:
X=np.ones((3,4), dtype=int)
print(X)
print(X.dtype)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
int64


### Create arrays containing default values

In [27]:
Y=np.full((3,4),-1)
print(Y)

[[-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]]


In [29]:
Y.dtype # by default it uses the datatype of the argument here we have passed -1 which is int

dtype('int64')

### Creating an Identity matrix

In [30]:
x=np.eye(5)
print(x)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [31]:
x.dtype

dtype('float64')

### Creating a diagonal matrix

In [33]:
x=np.diag([20,30,40,50])
print(x)
print(x.dtype)

[[20  0  0  0]
 [ 0 30  0  0]
 [ 0  0 40  0]
 [ 0  0  0 50]]
int64


# Creating arrays from a given range of values

In [34]:
x=np.arange(0,10,2)
# here the endpoint is excluded by default
print(x)

[0 2 4 6 8]


In [35]:
x=np.linspace(1,20,10)
# in linspace the endpoint is included by default
print(x)

[ 1.          3.11111111  5.22222222  7.33333333  9.44444444 11.55555556
 13.66666667 15.77777778 17.88888889 20.        ]


In [38]:
#we can use the following to exlude the endpoints
x=np.linspace(0,25,10, endpoint=False)
print(x)

[ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20.  22.5]


### Converting a 1d array to 2d array(Reshaping the arrays)

In [39]:
x=np.arange(20)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [44]:
x=np.reshape(x, (4,5))
# the number of element should be same as the given array
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [46]:
# we can use these methods in sequence by without having a need to pass the x array 
x=np.arange(20).reshape(10,2)
x

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [48]:
# Simillar thing can be done with the linspace() 
x=np.linspace(1,20,10,endpoint=False).reshape(5,2)
x

array([[ 1. ,  2.9],
       [ 4.8,  6.7],
       [ 8.6, 10.5],
       [12.4, 14.3],
       [16.2, 18.1]])

# Creating arrays of random values

In [49]:
x=np.random.random((3,3))
print(x)

[[0.70010342 0.09401344 0.8503016 ]
 [0.6603992  0.77224905 0.15336035]
 [0.15559438 0.54426054 0.27769468]]


In [52]:
x=np.random.randint(1,10,(3,2))
print(x)


[[2 5]
 [5 8]
 [3 8]]


In [53]:
x=np.random.normal(0,0.1, size=(1000,1000))
print(x)
# mean 0 
#statndard deviation 0.1

[[ 1.82251047e-02 -1.32741420e-01  2.54370522e-01 ... -1.47187358e-01
   2.52238294e-03  3.98739788e-02]
 [ 2.27340017e-01  2.50966736e-04  8.16298787e-02 ... -5.72557099e-02
  -7.95089474e-02 -1.10349755e-01]
 [-2.92597464e-02  1.30688593e-01 -1.21004653e-01 ...  1.27168815e-01
  -6.04232346e-02  2.10167436e-03]
 ...
 [-1.15494752e-01  1.47978049e-01  1.68841717e-02 ... -8.47511968e-02
   3.10439797e-01  1.78533863e-02]
 [-1.55416649e-01  1.76592930e-01 -1.58703724e-02 ...  9.92375989e-02
  -1.49038523e-02  5.74698856e-02]
 [-4.06403430e-02 -1.09340517e-02  2.76744535e-02 ...  1.78901940e-01
   6.20917034e-02  5.31283941e-02]]


In [57]:
print("Mean", x.mean())
print("Standard Deviation", x.std())
print("Maximum", x.max())
print("Minimum", x.min())
print("Positve count", (x>0).sum())
print("Negative count", (x<0).sum())

Mean 4.28111198364702e-05
Standard Deviation 0.09998674734021464
Maximum 0.4609660919710106
Minimum -0.48305418258040655
Positve count 500280
Negative count 499720


# Data Manipulations in Numpy Arrays

### Aceessing Elements

In [3]:
x=np.array([1,2,3,4,5])
print(x)

[1 2 3 4 5]


In [4]:
print("1st element ", x[0])
print("2nd Element",x[1])
print("3rd Element", x[2])

1st element  1
2nd Element 2
3rd Element 3


In [5]:
print("Last element", x[-1])
print("First element", x[-5])

Last element 5
First element 1


In [6]:
x=np.arange(1,10).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Updating values

In [8]:
x[0,0]=-1
x

array([[-1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

### Deleting Elements


In [9]:
x=np.arange(1,6)
print(x)

[1 2 3 4 5]


In [10]:
x=np.delete(x,[0,2])
x

array([2, 4, 5])

In [28]:
x=np.arange(1,10).reshape(3,3)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [29]:
x=np.delete(x,0,axis=0)
print(x)
x=np.delete(x,[0,2], axis=1)
print('\n',x)

[[4 5 6]
 [7 8 9]]

 [[5]
 [8]]


### insertion in the numpy arrays

In [40]:
y=np.array([[1,2,3],[7,8,9]])
y


array([[1, 2, 3],
       [7, 8, 9]])

In [38]:
z=np.insert(y,1,[4,5,6],axis=0)
z

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
V=np.insert(y,1,5,axis=1)
V

array([[1, 5, 2, 3],
       [7, 5, 8, 9]])

### Stacking the arrays

In [43]:
x=np.array([1,2])
x

array([1, 2])

In [44]:
y=np.array([[3,4],[5,6]])
y

array([[3, 4],
       [5, 6]])

In [47]:
a=np.vstack((x,y))
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [49]:
b=np.hstack((y,x.reshape(2,1)))
b

array([[3, 4, 1],
       [5, 6, 2]])

# Slicing in the numpy arrays

In [50]:
x=np.arange(1,21).reshape(4,5)
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [53]:
a=x[1:4,2:5]
print(a)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [54]:
b=x[:,2]
print(b)

[ 3  8 13 18]


In [55]:
c=x[:,2:3]
print(c)

[[ 3]
 [ 8]
 [13]
 [18]]


# Boolean Indexing

In [57]:
x=np.arange(25).reshape(5,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [58]:
print(x[x<=7])

[0 1 2 3 4 5 6 7]


In [59]:
x[(x>10) & (x<17)]=-1
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 -1 -1 -1 -1]
 [-1 -1 17 18 19]
 [20 21 22 23 24]]


# Set Operations

In [60]:
x=np.array([1,2,3,4,5])
y=np.array([6,7,2,8,4])
print(np.intersect1d(x,y))
print(np.setdiff1d(x,y))
print(np.union1d(x,y))

[2 4]
[1 3 5]
[1 2 3 4 5 6 7 8]


# Sorting

In [61]:
x=np.random.randint(1,11,size=10)
print(x)

[ 4  4  3  4  7  7 10  6  3  2]


In [64]:
print(np.sort(x)) # this doesn't sorts the original array
print(x)

[ 2  3  3  4  4  4  6  7  7 10]
[ 4  4  3  4  7  7 10  6  3  2]


In [65]:
print(np.sort(np.unique(x)))

[ 2  3  4  6  7 10]


In [ ]:
#inplace soriting
x.sort()
print(x)

In [70]:
x=np.random.randint(1,11,size=(5,5))
print(x)

[[ 5  6  5 10 10]
 [ 6  5  8  4  3]
 [ 7  2  9  7  8]
 [ 4  3 10  1  5]
 [ 4  7  7  7  5]]


In [71]:
print(np.sort(x))

[[ 5  5  6 10 10]
 [ 3  4  5  6  8]
 [ 2  7  7  8  9]
 [ 1  3  4  5 10]
 [ 4  5  7  7  7]]


In [72]:
print(np.sort(x, axis=0)) #sort by row


[[ 4  2  5  1  3]
 [ 4  3  7  4  5]
 [ 5  5  8  7  5]
 [ 6  6  9  7  8]
 [ 7  7 10 10 10]]


In [73]:
print(np.sort(x, axis=1)) #column sorting

[[ 5  5  6 10 10]
 [ 3  4  5  6  8]
 [ 2  7  7  8  9]
 [ 1  3  4  5 10]
 [ 4  5  7  7  7]]


# Arithmatic operations on numpy

In [77]:
x=np.array([1,2,3,4,5])
y=np.array([6,7,2,8,4])
print(x+y)
print(np.add(x,y))
print(x*y)
print(np.multiply(x,y))
print(y/x)
print(np.divide(y,x))

[ 7  9  5 12  9]
[ 7  9  5 12  9]
[ 6 14  6 32 20]
[ 6 14  6 32 20]
[6.         3.5        0.66666667 2.         0.8       ]
[6.         3.5        0.66666667 2.         0.8       ]


In [79]:
x=np.array([1,2,3,4]).reshape(2,2)
y=np.array([5,6,7,8]).reshape(2,2)

[[1 2]
 [3 4]]


array([[5, 6],
       [7, 8]])

In [80]:
print(x+y)
print(x-y)
print(x*y)
print(x/y)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [81]:
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [82]:
print(np.exp(x))

[[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]


In [83]:
np.power(x,2)

array([[ 1,  4],
       [ 9, 16]])

In [86]:
print("Average of the all values is", x.mean())
print("Sum of the values: ", x.sum())

Average of the all values is 2.5
Sum of the values:  10


In [88]:
print("Average of columns:", x.mean(axis=0))
print("Average of the rows:", x.mean(axis=1))

Average of columns: [2. 3.]
Average of the rows: [1.5 3.5]


In [89]:
# same can be done with sum, std etc
print("Sum of all elements:", x.sum())
print("Sum of columns:", x.sum(axis=0))
print("Sum of the rows:", x.sum(axis=1))

Sum of all elements: 10
Sum of columns: [4 6]
Sum of the rows: [3 7]


In [90]:
print(x.std())

1.118033988749895


In [92]:
print(np.median(x))

2.5


In [93]:
print(x.max())

4


In [94]:
print(x.min())

1


### adding single element to np arrays

In [95]:
print(3+x)

[[4 5]
 [6 7]]


In [96]:
print(x-3)

[[-2 -1]
 [ 0  1]]


In [97]:
print(x*3)

[[ 3  6]
 [ 9 12]]


In [98]:
print(x/3)

[[0.33333333 0.66666667]
 [1.         1.33333333]]


In [99]:
x=np.arange(9).reshape(3,3)
y=np.arange(3).reshape(1,3)
print(x)
print(y)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]]


In [100]:
print(x+y)

[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]]


In [101]:
print(x-y)

[[0 0 0]
 [3 3 3]
 [6 6 6]]


In [ ]:
print(y-x)